name: xfile
description: >-
  Extend on dart `File` for more helpful functions.
version: 1.1.0
homepage: https://github.com/Arxing/dart-xfile
author: Arxing <meiswind711108@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
