name: xfile
description: A library used like java class 'File'.
version: 1.0.0
homepage: https://github.com/Arxing/dart-xfile
author: arxing <meiswind711108@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
